import Link from "next/link";
import { fetchMeetingDetail } from "@/components/api";
import { Transcript } from "@/components/Transcript";
import { StubPanel } from "@/components/StubPanel";
import { ErrorBanner } from "@/components/ErrorBanner";
import {
  formatDateTime,
  formatDuration,
  lineCountLabel,
} from "@/components/format";

/**
 * Meeting detail (`/meetings/:id`) — Phase 1.
 *
 * The transcript is REAL: a Server Component reads GET /api/sessions/:id and
 * renders the meeting header (title, date, duration, line count) plus the
 * speaker-labelled, timestamped transcript in capture order. Alongside it are
 * the Phase-1 LABELLED STUB panels (AI Summary, Q&A) — visibly present but
 * non-functional and marked "Coming soon" so the user sees the vision without
 * ever mistaking a placeholder for a bug.
 *
 * States handled: 404 → friendly "meeting not found"; API/network error →
 * inline retry banner; loading → the sibling `loading.tsx` skeleton.
 */

export const dynamic = "force-dynamic";

export default async function MeetingDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;

  let meeting;
  try {
    meeting = await fetchMeetingDetail(id);
  } catch (err) {
    const message =
      err instanceof Error ? err.message : "Could not load this meeting.";
    return (
      <div className="space-y-4">
        <BackLink />
        <ErrorBanner message={message} />
      </div>
    );
  }

  if (meeting === null) {
    return <NotFound />;
  }

  const failed = meeting.titleStatus === "failed";

  return (
    <div className="space-y-6">
      <BackLink />

      <header className="space-y-2">
        <div className="flex flex-wrap items-center gap-3">
          <h1
            data-testid="meeting-title"
            className="text-xl font-semibold text-slate-900"
          >
            {meeting.title}
          </h1>
          {failed && (
            <span
              data-testid="retitle-affordance"
              title="Auto-titling failed — you can re-title this later"
              className="rounded-full bg-amber-50 px-2 py-0.5 text-xs font-medium text-amber-700 ring-1 ring-amber-200"
            >
              titling failed · re-title
            </span>
          )}
        </div>
        <dl className="flex flex-wrap items-center gap-x-4 gap-y-1 text-sm text-slate-500">
          <dd data-testid="meeting-date" className="font-medium text-slate-600">
            {formatDateTime(meeting.startedAt)}
          </dd>
          <dd className="text-slate-300" aria-hidden="true">
            •
          </dd>
          <dd data-testid="meeting-duration">
            {formatDuration(meeting.durationMs)}
          </dd>
          <dd className="text-slate-300" aria-hidden="true">
            •
          </dd>
          <dd data-testid="meeting-linecount">
            {lineCountLabel(meeting.lineCount)}
          </dd>
        </dl>
      </header>

      <div className="grid grid-cols-1 gap-6 lg:grid-cols-[1fr_20rem]">
        {/* Primary column: the REAL transcript. */}
        <section aria-label="Transcript">
          <h2 className="mb-2 text-sm font-semibold uppercase tracking-wide text-slate-400">
            Transcript
          </h2>
          <div className="rounded-lg border border-slate-200 bg-white p-3">
            <Transcript lines={meeting.lines} />
          </div>
        </section>

        {/* Side column: Phase-1 labelled STUB panels. */}
        <aside className="space-y-4">
          <StubPanel
            title="AI Summary"
            phase="Phase 2"
            description="A TL;DR, key points and action items with owners, generated by Gemini"
          >
            <ul className="space-y-1 text-sm">
              <li className="font-medium text-slate-400">TL;DR</li>
              <li>• Key point / decision</li>
              <li>• Key point / decision</li>
              <li className="pt-1 font-medium text-slate-400">Action items</li>
              <li>• Task — owner</li>
            </ul>
          </StubPanel>

          <StubPanel
            title="Ask about this meeting"
            phase="Phase 3"
            description="Grounded Q&A with jump-to-moment citations into this transcript"
          >
            <div className="space-y-2 text-sm">
              <div className="rounded-md border border-slate-200 bg-white/60 px-3 py-2 text-slate-400">
                Ask a question about this meeting…
              </div>
              <p className="text-xs">
                Answers will cite the exact transcript lines they come from.
              </p>
            </div>
          </StubPanel>
        </aside>
      </div>
    </div>
  );
}

function BackLink() {
  return (
    <Link
      href="/"
      data-testid="back-to-library"
      className="inline-flex items-center gap-1 text-sm text-slate-500 hover:text-slate-700"
    >
      <span aria-hidden="true">←</span> Back to library
    </Link>
  );
}

function NotFound() {
  return (
    <div className="space-y-4">
      <BackLink />
      <div
        data-testid="meeting-not-found"
        className="rounded-lg border border-dashed border-slate-300 bg-white p-10 text-center"
      >
        <h1 className="text-base font-semibold text-slate-700">
          That meeting doesn&apos;t exist
        </h1>
        <p className="mx-auto mt-2 max-w-md text-sm text-slate-500">
          We couldn&apos;t find a meeting with that id. It may have been removed.
        </p>
        <Link
          href="/"
          className="mt-4 inline-block rounded-md border border-slate-300 bg-white px-3 py-1.5 text-sm font-medium text-slate-700 hover:bg-slate-50"
        >
          Back to library
        </Link>
      </div>
    </div>
  );
}
